[package]
name = "treers"
version = "0.1.0"
authors = ["Horki <ivanzvonimirhorvat@gmail.com>"]
categories = ["data-structures", "algorithms"]
edition = "2018"
repository = "https://github.com/Horki/treers"
readme = "./README.md"
license = "MIT"

[dependencies]
